spring.application.name=A3OSU

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.liquibase.change-log=classpath:config/liquibase/master.xml
spring.liquibase.enabled=true

api.security.token.secret=${JWT_SECRET}

primary.datasource.driverClassName=com.mysql.cj.jdbc.Driver
primary.datasource.jdbc-url=${APP_DATABASE_JDBC_URL}
primary.datasource.username=${APP_DATABASE_JDBC_USER}
primary.datasource.password=${APP_DATABASE_JDBC_PASSWORD}